name: PR - Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"

      - name: Run linter
        uses: py-actions/flake8@v2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # Use Python 3.8, the same Python version used by the Azure Functions Core Tools,
          # otherwise the Azure Function App will start with errors and its Functions will not run
          python-version: "3.8"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install Azure Function App dependencies
        run: pip install -r requirements.txt

      - name: Run Azure Function App
        run: func host start &

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          curl -I http://127.0.0.1:7071
          newman run Web_Scraping_API.postman_collection.json -e Web_Scraping_API.postman_environment.json -r htmlextra --reporter-htmlextra-export TestReport.html

      - uses: actions/upload-artifact@v3
        with:
          path: TestReport.html
