name: PR - Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
      - name: Run linter
        uses: py-actions/flake8@v2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Azure Function App
        run: |
          pip install -r requirements.txt
          func host start
          sleep 5

      - name: Run Postman collection
        run: |
          mkdir -p testResults
          newman run Web_Scraping_API.postman_collection.json -e Web_Scraping_API.postman_environment.json -r htmlextra --reporter-htmlextra-export ./testResults/testReport.html

      - uses: actions/upload-artifact@v3
        with:
          name: TestReports
          path: testResults
