name: PR - Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"

      - name: Run linter
        uses: py-actions/flake8@v2

  test:
    uses: ./.github/workflows/test.yml
